{% set version = "1.9.0" %}

package:
  name: py6s
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Py6S/Py6S-{{ version }}.tar.gz
  sha256: 7747b61dfb0543f4a255e8d734df6bae9d15b79f9d863b30c6bba01409dd1441

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pysolar 0.6
    - matplotlib-base
    - scipy
    - numpy
    - sixs
    - python-dateutil

test:
  imports:
    - Py6S
    - Py6S.Params
    - Py6S.SixSHelpers

about:
  home: http://py6s.rtwilson.com/
  license: LGPL-3.0-only
  license_file: COPYING.LESSER
  license_family: LGPL

  summary: A Python interface to the 6S Radiative Transfer Model

  description: |
    A wrapper for the 6S Radiative Transfer Model to make it easy to
    run simulations with a variety of input parameters, and to produce outputs
    in an easily processable form.

  doc_url: http://py6s.readthedocs.io/en/latest/
  dev_url: https://github.com/robintw/py6s

extra:
  recipe-maintainers:
    - robintw
