{% set version = "1.8.2" %}

package:
  name: py6s
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Py6S/Py6S-{{ version }}.tar.gz
  sha256: 296b09db5e56ef82aced031aa06219c2901ef598f67c0e47d07c566bfb4b87db

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pysolar 0.6
    - matplotlib-base
    - scipy
    - numpy
    - sixs

test:
  imports:
    - Py6S
    - Py6S.Params
    - Py6S.SixSHelpers

about:
  home: http://py6s.rtwilson.com/
  license: LGPL-3.0
  license_file: COPYING.LESSER
  license_family: LGPL

  summary: A Python interface to the 6S Radiative Transfer Model

  description: |
    A wrapper for the 6S Radiative Transfer Model to make it easy to
    run simulations with a variety of input parameters, and to produce outputs
    in an easily processable form.

  doc_url: http://py6s.readthedocs.io/en/latest/
  dev_url: https://github.com/robintw/py6s

extra:
  recipe-maintainers:
    - robintw
