travis:
  secure:
    BINSTAR_TOKEN: DXmq2SG1SopmNPWu6fXWK3UrLNULNgB1X4KeiywEdIxi3gojREMIF/E/4VmCOnPiNoSbFbZP8Gl2wbu7X+uowGyOruQg3WbYLK5QVbpfS29zDx7732jhhENbOjjS/0hWoQFNZKOx4yMyAsUlW3MjT+DasuDuUPQNJfYbZ75o16+3k1Ey1HIAXVQCyaZI+7jigvvBtTxjqW4dBQet3Juul7O18B1lKrKYU8vrHIY02buV6QrIneDaebSceGfTfrEAbRULF6mBQxCaKmy8RGJ6BKzmSOYffz0hkseCX0Xh8YKVVlmVFhvqzm+wOHAONjlvB/TK93z8KwHEbJlr2QEtS2Fs+dvgmG6/7Ylh0H3iPSDYkTBAkEKFKImBiRb8/eJh+6N6FiG3HLAod7qOhwOj301UUS3vuoydB3bgNMUuKQi/gvAvsi3ceCqZzmPnCs1y6AyBEc/slR9/hdRWyek6t/pUsCP1jkUcnrJ7wlBfrMkwbDYBd7+9p0RUcmug53WzNNKA9vlWFKeU2R/JowYWqTqxv9XxXQOp2UTHr5ai0TvCD1H/3TRWB2T28O8136b3kEiJoAkVoNr/L8qxD610Hto3U+En6mcYmgJ+F85QDp584MyXU4ywPWrMRaH77V9pAcOqs9Ad4Nwbrc12W3gIWl46JfibVbroGMg1WE1HzwE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
